const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Fundo: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{Jogador: 0},
	{Fixar: 0},
	{Animação: 0},
	{Âncora: 0},
	{pontuação: 0},
	{Teclado: 0},
	{Senóide: 0},
	{colecionavel: 0},
	{Sólido: 0},
	{base02: 0},
	{Espinho2: 0},
	{base04: 0},
	{Espinho: 0},
	{ação: 0},
	{Fantasma: 0},
	{marcador: 0},
	{Fimdefase: 0},
	{Áudio: 0},
	{base01: 0},
	{base03: 0},
	{morte: 0},
	{Fundo2: 0},
	{Fimdejogo: 0},
	{Menu: 0},
	{Play: 0},
	{Mouse: 0},
	{Sprite: 0},
	{pontos: 0},
	{pontos2: 0}
];

self.InstanceType = {
	Fundo: class extends self.ITiledBackgroundInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Animação: class extends self.ISpriteInstance {},
	pontuação: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	colecionavel: class extends self.ISpriteInstance {},
	base02: class extends self.ISpriteInstance {},
	Espinho2: class extends self.ITiledBackgroundInstance {},
	base04: class extends self.ISpriteInstance {},
	Espinho: class extends self.ISpriteInstance {},
	Fantasma: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	Fimdefase: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	base01: class extends self.ISpriteInstance {},
	base03: class extends self.ISpriteInstance {},
	morte: class extends self.ISpriteInstance {},
	Fundo2: class extends self.ISpriteInstance {},
	Fimdejogo: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {}
}